version = 1

[install]
abctl.pkg-path = "abctl"

[vars]

[hook]
on-activate = '''
'''

[profile]
common = '''
echo ""
echo "     â•”â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•—"
echo "     â•‘                                     â•‘"
echo "     â•‘  Compile and flash your firmware:   â•‘"
echo "     â•‘  ğŸ‘‰ abctl                           â•‘"
echo "     â•‘                                     â•‘"
echo "     â•‘  Read: https://www.airbyte.com      â•‘"
echo "     â•‘                                     â•‘"
echo "     â•šâ•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•"
echo ""
'''

[services]

[options]
systems = [
  "aarch64-linux",
  "x86_64-linux",
]
