version = 1


[install]
mac-app-util.flake = "github:hraban/mac-app-util"
jq.pkg-path = "jq"

# Example package to test
#raycast.pkg-path = "raycast"


[hook]
on-activate = '''
FLOX_ENV_NAME=$(echo $_FLOX_ACTIVE_ENVIRONMENTS | jq -r '.[0].pointer.name')
FLOX_ENV_APPS="$HOME/Applications/Flox ($FLOX_ENV_NAME) Apps"

if [[ -d $FLOX_ENV_APPS ]]; then
  rm -rf "$FLOX_ENV_APPS"
fi

if [ -d $FLOX_ENV/Applications ]; then 
  mac-app-util sync-trampolines \
    "$FLOX_ENV/Applications" \
    "$FLOX_ENV_APPS"
fi
'''


[options]
systems = [
  "aarch64-darwin",
  "x86_64-darwin",
]
