version = 1

[install]
# That's literally it, that's all you need
qmk.pkg-path = "qmk"

[vars]

[hook]
on-activate = '''
echo ""
echo "     â•”â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•—"
echo "     â•‘                                     â•‘"
echo "     â•‘  Compile and flash your firmware:   â•‘"
echo "     â•‘  ğŸ‘‰ qmk compile                     â•‘"
echo "     â•‘  ğŸ‘‰ qmk flash                       â•‘"
echo "     â•‘                                     â•‘"
echo "     â•šâ•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•â•"
echo ""
'''


[profile]

[services]

[options]
systems = ["aarch64-darwin", "aarch64-linux", "x86_64-darwin", "x86_64-linux"]
